"""Rules data for the Fallout 2d20 character generator.

Numbers (stats, requirements, weights) follow the Core Rulebook's character
creation and equipment chapters. All descriptive text is written for this tool
as short summaries -- check the book for the full rules wording.
"""

SPECIAL = ["STR", "PER", "END", "CHA", "INT", "AGI", "LCK"]

SKILLS = [
    ("Athletics", "STR"), ("Barter", "CHA"), ("Big Guns", "END"),
    ("Energy Weapons", "PER"), ("Explosives", "PER"), ("Lockpick", "PER"),
    ("Medicine", "INT"), ("Melee Weapons", "STR"), ("Pilot", "PER"),
    ("Repair", "INT"), ("Science", "INT"), ("Small Guns", "AGI"),
    ("Sneak", "AGI"), ("Speech", "CHA"), ("Survival", "END"),
    ("Throwing", "AGI"), ("Unarmed", "STR"),
]
SKILL_ATTR = dict(SKILLS)
SKILL_NAMES = [s for s, _ in SKILLS]

# ---------------------------------------------------------------- weapons
# skill, damage, effects, dmg type, fire rate, range, qualities, weight
W = lambda skill, dmg, eff, typ, rate, rng, qual, wt, ammo=None: dict(
    skill=skill, dmg=dmg, eff=eff, type=typ, rate=rate, range=rng,
    qual=qual, wt=wt, ammo=ammo)

WEAPONS = {
    "10mm Pistol": W("Small Guns", 4, "-", "Phys", 2, "C", "Close Qtrs, Reliable", 4, "10mm"),
    ".44 Pistol": W("Small Guns", 6, "Vicious", "Phys", 1, "C", "Close Qtrs", 4, ".44"),
    "Hunting Rifle": W("Small Guns", 6, "Piercing 1", "Phys", 0, "M", "Two-Handed", 10, ".308"),
    "Pipe Bolt-Action": W("Small Guns", 5, "Piercing 1", "Phys", 0, "C", "Unreliable", 3, ".308"),
    "Pipe Gun": W("Small Guns", 3, "-", "Phys", 2, "C", "Close Qtrs, Unreliable", 2, ".38"),
    # pipe gun + full stock
    "Pipe Rifle": W("Small Guns", 3, "-", "Phys", 2, "C", "Unreliable, Two-Handed", 3, ".38"),
    # pipe bolt-action + .308 receiver + full stock
    "Heavy Pipe Bolt-Action": W("Small Guns", 7, "Piercing 1", "Phys", 0, "C", "Unreliable, Two-Handed", 8, ".308"),
    "Laser Pistol": W("Energy Weapons", 4, "Piercing 1", "Energy", 2, "C", "Close Qtrs", 4, "Fusion Cell"),
    "Combat Knife": W("Melee Weapons", 3, "Piercing 1", "Phys", "-", "-", "-", 1),
    "Machete": W("Melee Weapons", 3, "Piercing 1", "Phys", "-", "-", "-", 2),
    "Baseball Bat": W("Melee Weapons", 4, "-", "Phys", "-", "-", "Two-Handed", 3),
    "Tire Iron": W("Melee Weapons", 3, "-", "Phys", "-", "-", "-", 2),
    "Lead Pipe": W("Melee Weapons", 3, "-", "Phys", "-", "-", "-", 3),
    "Pool Cue": W("Melee Weapons", 3, "-", "Phys", "-", "-", "Two-Handed", 1),
    "Switchblade": W("Melee Weapons", 2, "Piercing 1", "Phys", "-", "-", "Concealed", 1),
    "Pipe Wrench": W("Melee Weapons", 3, "-", "Phys", "-", "-", "-", 2),
    "Rolling Pin": W("Melee Weapons", 3, "-", "Phys", "-", "-", "-", 1),
    "Baton": W("Melee Weapons", 3, "-", "Phys", "-", "-", "-", 2),
    "Board": W("Melee Weapons", 4, "-", "Phys", "-", "-", "Two-Handed", 3),
    "Knuckles": W("Unarmed", 3, "-", "Phys", "-", "-", "Concealed", "<1"),
    "Unarmed Strike": W("Unarmed", 2, "-", "Phys", "-", "-", "-", "-"),
    "Throwing Knives": W("Throwing", 3, "Piercing 1", "Phys", "-", "C", "Concealed, Thrown", "<1"),
    "Tomahawks": W("Throwing", 4, "Piercing 1", "Phys", "-", "C", "Suppressed, Thrown", "<1"),
    "Molotov Cocktail": W("Explosives", 4, "Persistent", "Energy", "-", "M", "Blast, Thrown", 1),
    "Baseball Grenade": W("Explosives", 5, "-", "Phys", "-", "M", "Blast, Thrown", 1),
    # Mister Handy arm attachments (built in, so no weight)
    "10mm Auto Pistol Arm": W("Small Guns", 3, "Burst", "Phys", 4, "C", "Close Qtrs, Inaccurate", "-", "10mm"),
    "Buzz-Saw Arm": W("Melee Weapons", 3, "Piercing 1", "Phys", "-", "-", "-", "-"),
    "Flamer Arm": W("Big Guns", 3, "Burst, Persist., Spread", "Energy", 4, "C", "Debilitating, Inaccurate", "-", "Flamer Fuel"),
    "Laser Emitter Arm": W("Energy Weapons", 4, "Piercing 1", "Energy", 2, "C", "Close Qtrs", "-", "Fusion Cell"),
    "Pincer Arm": W("Unarmed", 2, "-", "Phys", "-", "-", "-", "-"),
}
ARM_WEAPON = {"10mm Auto Pistol": "10mm Auto Pistol Arm", "Buzz-Saw": "Buzz-Saw Arm",
              "Flamer": "Flamer Arm", "Laser Emitter": "Laser Emitter Arm", "Pincer": "Pincer Arm"}

# ---------------------------------------------------------------- apparel
# phys, energy, rad, locations, weight, layer ("cloth" | "outfit" | "armor" | "head")
A = lambda p, e, r, locs, wt, layer: dict(p=p, e=e, r=r, locs=locs, wt=wt, layer=layer)
BODY = ["larm", "rarm", "torso", "lleg", "rleg"]
APPAREL = {
    "Tough Clothing": A(1, 1, 0, BODY, 3, "cloth"),
    "Casual Clothing": A(0, 0, 0, BODY, 2, "cloth"),
    "Harness": A(0, 0, 0, BODY, 1, "cloth"),
    "Vault Jumpsuit": A(0, 1, 2, BODY, 1, "cloth"),
    "Drifter Outfit": A(1, 2, 0, BODY, 10, "outfit"),
    "Brotherhood Fatigues": A(2, 2, 2, BODY, 4, "outfit"),
    "Brotherhood Scribe's Armor": A(1, 2, 2, BODY, 4, "outfit"),
    "Lab Coat": A(0, 0, 0, BODY, 2, "outfit"),
    "Formal Clothing": A(0, 0, 0, BODY, 2, "outfit"),
    "Brotherhood Hood": A(0, 1, 0, ["head"], "<1", "head"),
    "Brotherhood Scribe's Hat": A(0, 2, 0, ["head"], "<1", "head"),
    "Formal Hat": A(0, 0, 0, ["head"], "<1", "head"),
    "Vault-Tec Security Helmet": A(2, 0, 0, ["head"], 2, "head"),
    "Vault-Tec Security Armor": A(2, 0, 2, BODY, 8, "armor"),
    "Raider Chest Piece": A(1, 1, 0, ["torso"], 7, "armor"),
    "Raider Arm (L)": A(1, 1, 0, ["larm"], 3, "armor"),
    "Raider Arm (R)": A(1, 1, 0, ["rarm"], 3, "armor"),
    "Raider Leg (L)": A(1, 1, 0, ["lleg"], 3, "armor"),
    "Raider Leg (R)": A(1, 1, 0, ["rleg"], 3, "armor"),
    "Raider Head Armor": A(1, 1, 0, ["head"], 3, "armor"),
    "Leather Chest Piece": A(1, 2, 0, ["torso"], 5, "armor"),
    "Leather Arm (L)": A(1, 2, 0, ["larm"], 2, "armor"),
    "Leather Arm (R)": A(1, 2, 0, ["rarm"], 2, "armor"),
    "Leather Leg (L)": A(1, 2, 0, ["lleg"], 2, "armor"),
    "Leather Leg (R)": A(1, 2, 0, ["rleg"], 2, "armor"),
}
ROBOT_PLATING = {
    "Standard Plating": dict(p=2, e=0, carry=0),
    "Mister Gutsy Plating": dict(p=2, e=2, carry=-10),
}

TRINKETS = [
    "A gold pocket watch", "A garbled holodisk", "A brightly colored bandanna",
    "A silver locket", "A medal", "A potted plant", "Tickets to a pre-war event",
    "A wedding ring", "A pre-war party invitation", "An engraved flip lighter",
    "Loaded casino dice", "An ID card", "A cosmetics case", "A musical instrument",
    "Broken eyeglasses", "A necklace made of junk", "Pages of an unfinished story",
    "An overdue library book", "A postcard with an address", "A pre-war neck-tie",
]

# --------------------------------------------------------------- perks
# name: (max ranks, requirements dict, flags, short summary written for this tool)
# Only perks a level-1 character can take are listed.
PERKS = {
    "Action Boy": (1, {}, {"gender": "M"}, "Extra AP-bought major action: no added difficulty."),
    "Action Girl": (1, {}, {"gender": "F"}, "Extra AP-bought major action: no added difficulty."),
    "Adamantium Skeleton": (3, {"END": 7}, {}, "Damage needed to crit you is +1 per rank."),
    "Adrenaline Rush": (1, {"STR": 7}, {}, "While hurt, STR counts as 10 for STR tests & melee."),
    "Animal Friend": (2, {"CHA": 6}, {}, "Mammals, lizards & insects may choose not to attack you."),
    "Aquaboy": (2, {"END": 5}, {"gender": "M"}, "No rads from swimming; hold breath twice as long."),
    "Aquagirl": (2, {"END": 5}, {"gender": "F"}, "No rads from swimming; hold breath twice as long."),
    "Armorer": (4, {"STR": 5, "INT": 6}, {}, "Can install rank 1 armor mods."),
    "Awareness": (1, {"PER": 7}, {}, "Aim at a Close target: next attack gains Piercing 1."),
    "Basher": (1, {"STR": 6}, {}, "Gun-bash attacks gain Vicious."),
    "Better Criticals": (1, {"LCK": 9}, {}, "Spend 1 Luck after hitting to make it a critical hit."),
    "Big Leagues": (1, {"STR": 8}, {}, "Two-handed melee weapons gain Vicious."),
    "Black Widow": (1, {"CHA": 6}, {"gender": "F"}, "Re-roll 1d20 on CHA tests vs men; +1 CD dmg vs them."),
    "Lady Killer": (1, {"CHA": 6}, {"gender": "M"}, "Re-roll 1d20 on CHA tests vs women; +1 CD dmg vs them."),
    "Blitz": (2, {"AGI": 9}, {}, "Move to melee & attack same turn: re-roll 1d20."),
    "Bloody Mess": (1, {"LCK": 6}, {}, "On a crit, roll 1 CD: an Effect adds an extra injury."),
    "Can Do!": (1, {"LCK": 5}, {"robot_no": True}, "+1 random food item when scavenging food."),
    "Cap Collector": (1, {"CHA": 5}, {}, "Nudge buy/sell prices 10% your way."),
    "Cautious Nature": (1, {"PER": 7}, {"excl": "Daring Nature"}, "Buying d20s with AP lets you re-roll 1d20."),
    "Center Mass": (1, {"AGI": 7}, {}, "Target torso at no extra difficulty; re-roll 1d20."),
    "Chem Resistant": (2, {"END": 7}, {"robot_no": True}, "Roll 1 fewer CD when checking for addiction."),
    "Chemist": (1, {"INT": 7}, {}, "Your crafted chems last twice as long; chem recipes."),
    "Comprehension": (1, {"INT": 6}, {}, "Magazine bonus used: roll 1 CD, Effect = use it again."),
    "Concentrated Fire": (1, {"PER": 8, "AGI": 6}, {}, "Spending extra ammo: re-roll up to 3 CD of damage."),
    "Daring Nature": (1, {"LCK": 7}, {"excl": "Cautious Nature"}, "Giving the GM AP for d20s lets you re-roll 1d20."),
    "Demolition Expert": (1, {"PER": 6, "LCK": 6}, {}, "Blast weapons gain Vicious; explosive recipes."),
    "Dogmeat": (1, {"CHA": 5}, {}, "A loyal dog companion travels with you."),
    "Entomologist": (1, {"INT": 7}, {}, "Attacks vs insects gain Piercing 1."),
    "Fast Metabolism": (3, {"END": 6}, {"robot_no": True}, "+1 HP per rank whenever you heal (not resting)."),
    "Faster Healing": (1, {"END": 6}, {"robot_no": True}, "First extra d20 on END+Survival self-healing is free."),
    "Finesse": (1, {"AGI": 9}, {}, "Once per fight, re-roll a whole damage roll for free."),
    "Ghost": (1, {"PER": 5, "AGI": 6}, {}, "First extra d20 on AGI+Sneak in darkness is free."),
    "Grim Reaper's Sprint": (1, {"LCK": 8}, {}, "On a kill roll 1 CD: Effect adds 2 AP to the pool."),
    "Gun Fu": (3, {"AGI": 10}, {}, "1 AP + 1 ammo: hit a second target in Close range."),
    "Hacker": (1, {"INT": 8}, {}, "Computer hacking difficulty -1."),
    "Healer": (3, {"INT": 7}, {}, "First Aid heals +1 HP per rank."),
    "Heave Ho!": (1, {"STR": 8}, {}, "1 AP: thrown weapon range +1 step."),
    "Hunter": (1, {"END": 6}, {}, "Attacks vs mutated beasts gain Vicious."),
    "Infiltrator": (1, {"PER": 8}, {}, "Re-roll 1d20 when picking locks on doors/containers."),
    "Inspirational": (1, {"CHA": 8}, {}, "Group AP pool maximum +1."),
    "Iron Fist": (2, {"STR": 6}, {}, "Unarmed attacks deal +1 CD."),
    "Jury Rigging": (1, {}, {}, "Patch items with no parts (it breaks on next complication)."),
    "Junktown Jerky Vendor": (1, {"CHA": 8}, {}, "CHA+Barter difficulty -1 when trading."),
    "Lead Belly": (2, {"END": 6}, {"robot_no": True}, "Re-roll the rads die from irradiated food/drink."),
    "Light Step": (1, {}, {}, "Spend AP to ignore AGI complications; re-roll vs traps."),
    "Master Thief": (1, {"PER": 8, "AGI": 9}, {}, "Spotting your lockpicking/pickpocketing is +1 harder."),
    "Medic": (1, {"INT": 8}, {}, "Re-roll 1d20 when treating injuries with First Aid."),
    "Meltdown": (1, {"PER": 10}, {}, "Energy-weapon kills explode and hurt nearby foes."),
    "Mister Sandman": (1, {"AGI": 9}, {}, "Silenced sneak attacks deal +2 CD."),
    "Moving Target": (1, {"AGI": 6}, {}, "+1 Defense after you Sprint."),
    "Mysterious Stranger": (1, {"LCK": 7}, {}, "Spend 1 Luck: a stranger may appear and shoot your foe."),
    "Night Person": (1, {"PER": 7}, {}, "Darkness penalties reduced by 1."),
    "Ninja": (1, {"AGI": 8}, {}, "Melee/unarmed sneak attacks deal +2 CD."),
    "Nuclear Physicist": (1, {"INT": 9}, {}, "Rad weapons hit harder; fusion cores +3 charges."),
    "Pain Train": (2, {"STR": 9, "END": 7}, {"pain_train": True}, "Charge enemies in Power Armor or as a super mutant."),
    "Paralyzing Palm": (1, {"STR": 8}, {}, "Targeted unarmed strikes gain Stun."),
    "Party Boy": (1, {"END": 6, "CHA": 7}, {"gender": "M", "robot_no": True}, "Never hooked on booze; drinks heal +2 HP."),
    "Party Girl": (1, {"END": 6, "CHA": 7}, {"gender": "F", "robot_no": True}, "Never hooked on booze; drinks heal +2 HP."),
    "Pathfinder": (1, {"PER": 6, "END": 6}, {}, "PER+Survival test halves overland travel time."),
    "Pharma Farma": (1, {"LCK": 6}, {}, "+1 random chem/medicine item when scavenging."),
    "Pickpocket": (3, {"PER": 8, "AGI": 8}, {}, "Ignore the first complication when pickpocketing."),
    "Piercing Strike": (1, {"STR": 7}, {}, "Unarmed & bladed attacks gain Piercing 1."),
    "Quick Draw": (1, {"AGI": 6}, {}, "Draw one weapon/item per turn for free."),
    "Quick Hands": (1, {"AGI": 8}, {}, "2 AP: double a gun's Fire Rate for one attack."),
    "Rad Resistance": (2, {"END": 8}, {}, "+1 radiation DR on every location."),
    "Refractor": (2, {"PER": 6, "LCK": 7}, {}, "+1 energy DR on every location."),
    "Scoundrel": (1, {"CHA": 7}, {}, "Ignore the first complication when lying."),
    "Scrounger": (3, {"LCK": 6}, {}, "Find +3 CD extra ammo when scavenging."),
    "Shotgun Surgeon": (1, {"STR": 5, "AGI": 7}, {}, "Shotguns gain Piercing 1."),
    "Size Matters": (3, {"END": 7, "AGI": 6}, {}, "Heavy weapons deal +1 CD per rank."),
    "Slayer": (1, {"STR": 8}, {}, "Spend 1 Luck: melee/unarmed hit becomes a critical."),
    "Smooth Talker": (1, {"CHA": 6}, {}, "Re-roll 1d20 on opposed Barter or Speech tests."),
    "Snakeater": (1, {"END": 7}, {}, "+2 poison DR."),
    "Sniper": (1, {"PER": 8, "AGI": 6}, {}, "Aimed two-handed Accurate shots pick their hit location."),
    "Solar Powered": (1, {"END": 7}, {}, "Heal 1 rad damage per hour in sunlight."),
    "Steady Aim": (1, {"STR": 8, "AGI": 7}, {}, "Aim: re-roll 2d20 on first attack or 1d20 on all."),
    "Strong Back": (3, {"STR": 5}, {"robot_no": True}, "+25 lbs carry weight per rank."),
    "Toughness": (2, {"END": 6, "LCK": 6}, {}, "+1 physical DR on every location."),
}

# --------------------------------------------------------------- archetypes
# special weights, skill weights, favoured perks
ARCHETYPES = {
    "Brawler": ({"STR": 5, "END": 3, "AGI": 1},
                {"Unarmed": 5, "Melee Weapons": 4, "Athletics": 3, "Survival": 1},
                ["Iron Fist", "Piercing Strike", "Paralyzing Palm", "Slayer", "Adrenaline Rush",
                 "Big Leagues", "Basher", "Pain Train", "Adamantium Skeleton"]),
    "Gunslinger": ({"AGI": 5, "PER": 2, "LCK": 1},
                   {"Small Guns": 5, "Sneak": 2, "Speech": 1, "Athletics": 1},
                   ["Quick Draw", "Center Mass", "Quick Hands", "Steady Aim", "Gun Fu", "Moving Target"]),
    "Sharpshooter": ({"PER": 5, "AGI": 3},
                     {"Small Guns": 5, "Sneak": 3, "Survival": 2},
                     ["Sniper", "Awareness", "Concentrated Fire", "Center Mass", "Night Person"]),
    "Smooth Operator": ({"CHA": 5, "INT": 2, "LCK": 1},
                        {"Speech": 5, "Barter": 4, "Sneak": 1, "Medicine": 1},
                        ["Smooth Talker", "Scoundrel", "Cap Collector", "Black Widow", "Lady Killer",
                         "Inspirational", "Junktown Jerky Vendor", "Dogmeat", "Animal Friend"]),
    "Tinkerer": ({"INT": 5, "PER": 2, "AGI": 1},
                 {"Repair": 5, "Science": 4, "Lockpick": 2, "Energy Weapons": 2},
                 ["Armorer", "Hacker", "Jury Rigging", "Comprehension", "Nuclear Physicist", "Chemist"]),
    "Field Medic": ({"INT": 5, "END": 1, "CHA": 1},
                    {"Medicine": 5, "Science": 3, "Survival": 2, "Speech": 1},
                    ["Medic", "Healer", "Chemist", "Faster Healing", "Fast Metabolism"]),
    "Infiltrator": ({"AGI": 5, "PER": 2, "LCK": 1},
                    {"Sneak": 5, "Lockpick": 4, "Throwing": 2, "Small Guns": 1},
                    ["Ninja", "Infiltrator", "Mister Sandman", "Light Step", "Ghost",
                     "Master Thief", "Pickpocket", "Night Person"]),
    "Survivalist": ({"END": 4, "PER": 2, "AGI": 1},
                    {"Survival": 5, "Athletics": 3, "Throwing": 2, "Medicine": 1},
                    ["Hunter", "Pathfinder", "Lead Belly", "Aquaboy", "Aquagirl", "Animal Friend",
                     "Snakeater", "Rad Resistance", "Entomologist", "Solar Powered", "Dogmeat"]),
    "Demolitionist": ({"PER": 4, "END": 2, "LCK": 2},
                      {"Explosives": 5, "Throwing": 3, "Repair": 2},
                      ["Demolition Expert", "Heave Ho!", "Bloody Mess", "Daring Nature"]),
    "Lucky Fool": ({"LCK": 6, "CHA": 1},
                   {"Barter": 2, "Sneak": 2, "Small Guns": 2, "Lockpick": 1, "Speech": 1},
                   ["Mysterious Stranger", "Better Criticals", "Bloody Mess", "Can Do!", "Scrounger",
                    "Daring Nature", "Grim Reaper's Sprint", "Pharma Farma"]),
    "Juggernaut": ({"END": 5, "STR": 3},
                   {"Big Guns": 4, "Athletics": 3, "Survival": 2, "Melee Weapons": 2},
                   ["Toughness", "Adamantium Skeleton", "Size Matters", "Rad Resistance",
                    "Strong Back", "Pain Train", "Chem Resistant"]),
    "Laser Jockey": ({"PER": 5, "INT": 2},
                     {"Energy Weapons": 5, "Science": 3, "Repair": 2},
                     ["Refractor", "Awareness", "Meltdown", "Concentrated Fire", "Nuclear Physicist"]),
}

# --------------------------------------------------------------- origins & packs
ORIGINS = {
    "Brotherhood Initiate": dict(race="human", packs=["Brotherhood Initiate", "Brotherhood Scribe"],
                                 arch=["Laser Jockey", "Sharpshooter", "Juggernaut", "Tinkerer", "Field Medic", "Gunslinger"]),
    "Ghoul": dict(race="ghoul", packs=["Mercenary", "Raider", "Settler", "Trader", "Wanderer"],
                  arch=list(ARCHETYPES)),
    "Super Mutant": dict(race="mutant", packs=["Brute", "Skirmisher"],
                         arch=["Brawler", "Juggernaut", "Sharpshooter", "Demolitionist", "Survivalist", "Gunslinger"]),
    "Mister Handy": dict(race="robot", packs=["Miss Nanny", "Mister Farmhand", "Mister Gutsy", "Mister Handy", "Nurse Handy"],
                         arch=["Tinkerer", "Field Medic", "Smooth Operator", "Juggernaut", "Laser Jockey", "Survivalist"]),
    "Survivor": dict(race="human", packs=["Mercenary", "Raider", "Settler", "Trader", "Wanderer"],
                     arch=list(ARCHETYPES)),
    "Vault Dweller": dict(race="human", packs=["Vault-Tec Resident", "Vault-Tec Security"],
                          arch=list(ARCHETYPES)),
}
PACK_AFFINITY = {
    "Brotherhood Initiate": ["Laser Jockey", "Sharpshooter", "Juggernaut", "Gunslinger"],
    "Brotherhood Scribe": ["Tinkerer", "Field Medic"],
    "Mercenary": ["Gunslinger", "Sharpshooter", "Brawler", "Juggernaut"],
    "Raider": ["Brawler", "Demolitionist", "Lucky Fool", "Juggernaut"],
    "Settler": ["Survivalist", "Tinkerer", "Field Medic", "Smooth Operator"],
    "Trader": ["Smooth Operator", "Lucky Fool", "Tinkerer"],
    "Wanderer": ["Infiltrator", "Survivalist", "Lucky Fool"],
    "Brute": ["Brawler", "Juggernaut", "Survivalist"],
    "Skirmisher": ["Sharpshooter", "Gunslinger", "Demolitionist"],
    "Miss Nanny": ["Smooth Operator", "Survivalist", "Field Medic"],
    "Mister Farmhand": ["Survivalist", "Tinkerer"],
    "Mister Gutsy": ["Juggernaut", "Laser Jockey", "Gunslinger"],
    "Mister Handy": ["Tinkerer", "Smooth Operator"],
    "Nurse Handy": ["Field Medic"],
    "Vault-Tec Resident": ["Tinkerer", "Field Medic", "Smooth Operator", "Infiltrator", "Lucky Fool", "Survivalist"],
    "Vault-Tec Security": ["Gunslinger", "Brawler", "Juggernaut", "Sharpshooter"],
}

ORIGIN_TRAITS = {
    "Brotherhood Initiate": ("The Chain That Binds",
                             "Extra tag skill (Energy Wpns, Science or Repair). Must obey the chain of command."),
    "Ghoul": ("Necrotic Post-Human",
              "Immune to rad damage & healed by it. Survival is tagged. Ageless but sterile; some folk distrust you."),
    "Super Mutant": ("Forced Evolution",
                     "STR & END +2 (max 12); INT & CHA max 6; skills max 4. Immune to rads & poison."),
    "Mister Handy": ("Mister Handy Robot",
                     "360-degree sensors; immune to rads & poison; no chems/food/rest; hovers; 150 lb carry; heal by repair."),
    "Vault Dweller": ("Vault Kid",
                      "END tests vs disease are easier. One extra tag skill. GM may trigger a Vault-experiment complication (+1 Luck)."),
}
SURVIVOR_TRAITS = {
    "Educated": "+1 tag skill. Failing an untagged skill test gives the GM 1 AP.",
    "Fast Shot": "2nd major action ranged attack costs 1 AP, but you can't Aim.",
    "Gifted": "+1 to two S.P.E.C.I.A.L.; max Luck points are LCK - 1.",
    "Heavy Handed": "+1 CD melee damage; melee complications on 19-20.",
    "Small Frame": "Re-roll 1d20 on AGI balance tests; carry weight 150 + 5xSTR.",
}

# --------------------------------------------------------------- names
HUMAN_FIRST = {
    "M": ["Nate", "Albert", "Butch", "Arthur", "Owyn", "Preston", "Robert", "Danse", "Benny",
          "Craig", "Arcade", "James", "Lucas", "Desmond", "Joshua", "Ulysses", "Sturges",
          "Elijah", "Moses", "Boone", "Vulpes", "Graham", "Paladin", "Herbert", "Max", "Tycho"],
    "F": ["Nora", "Amata", "Moira", "Sarah", "Piper", "Veronica", "Cait", "Tandi", "Myrna",
          "Trudy", "Sunny", "Christine", "Desdemona", "Glory", "Marcy", "Nadine", "Haylen",
          "Lucy", "Magnolia", "Cass", "Rose", "Jessica", "Dorothy", "Bea", "Leslie", "Lily"],
}
HUMAN_LAST = ["Cole", "Simms", "Lyons", "Maxson", "DeLoria", "Brown", "Garvey", "Wright",
              "MacCready", "Gannon", "Santangelo", "Cassidy", "Boone", "Kellogg", "Burke",
              "Murphy", "Ingram", "Kells", "Brandis", "Cabot", "MacLean", "Tenpenny",
              "Dashwood", "Abernathy", "House", "Valentine", "Danse", "Sturges", "Stone",
              "Moldaver", "Hawthorne", "Mercer"]
GHOUL_FIRST = {
    "M": ["Raul", "John", "Charon", "Gob", "Kent", "Roy", "Harold", "Set", "Winthrop",
          "Jason", "Cooper", "Oswald", "Crowley", "Barrows", "Ahzrukhal", "Bobbi"],
    "F": ["Carol", "Daisy", "Greta", "Tulip", "Bobbi", "Willow", "Hannah", "Mags", "Edith",
          "Penny", "Mama", "Dottie"],
}
GHOUL_LAST = ["Tejada", "Hancock", "Connolly", "Phillips", "Bright", "Howard", "Barrows",
              "Crowley"] + HUMAN_LAST[:12]
GHOUL_NICK = ["No-Nose", "Leatherface", "Crispy", "Old Bones", "Smoothskin-Hater", "Two-Teeth",
              "Glowing", "Patches"]
MUTANT_NAMES = ["Marcus", "Lily", "Fawkes", "Strong", "Leo", "Tabitha", "Neil", "Keane",
                "Davison", "Grahm", "Virgil", "Jacob", "Lou", "Swank", "Brontus"]
MUTANT_TITLES = ["Uncle", "Big", "Brother", "Sister", "Captain", "Little", "Old"]
ROBOT_NAMES = ["Codsworth", "Wadsworth", "Curie", "Ada", "Victor", "Rose", "Jenkins",
               "Ashworth", "Fitzgerald", "Pennyfeather", "Higgins", "Bartleby"]
ROBOT_TITLES = {"Miss Nanny": "Miss", "Mister Gutsy": "Sergeant", "Nurse Handy": "Nurse",
                "Mister Farmhand": "Farmer", "Mister Handy": "Mister"}

# --------------------------------------------------------------- gimmick text (original)
EPITHETS = {
    "STR": ["Two-Ton", "the Mountain", "Brahmin-Tosser", "Crowbar", "Ironarm"],
    "PER": ["Hawkeye", "Sniffer", "Eagle-Eye", "Whiskers", "Sharp-Ear"],
    "END": ["Iron-Gut", "Leadbelly", "Rad-Sponge", "Old Leather", "Unkillable"],
    "CHA": ["Silver-Tongue", "Sweet-Talk", "Smiles", "Darling", "Honey"],
    "INT": ["Professor", "Gears", "Brainbox", "Four-Eyes", "Doc"],
    "AGI": ["Quickstep", "Shadow", "Slick", "Twitch", "Jackrabbit"],
    "LCK": ["Lucky", "Lucky Penny", "Jackpot", "Snake-Eyes", "Clover"],
}
HIGH_LINES = {
    "STR": ["opens jammed vault doors bare-handed", "carries a whole fridge around 'just in case'",
            "has never lost an arm-wrestle (the deathclaw story is disputed)"],
    "PER": ["can smell a radroach nest three rooms away", "spots tripwires before they're even set",
            "counts the bullets in every gun pointed at them"],
    "END": ["eats week-old mirelurk without blinking", "once napped straight through a radstorm",
            "treats stimpaks as a polite suggestion"],
    "CHA": ["once talked a raider gang into a group hug", "gets a discount from every merchant, even robots",
            "can make a death threat sound like a dinner invite"],
    "INT": ["rebuilds Pip-Boys for fun", "corrects the grammar on terminals while hacking them",
            "keeps a notebook of every pre-war schematic ever seen"],
    "AGI": ["reloads before the casing hits the ground", "walks over broken glass without a sound",
            "has never once stepped in a bear trap"],
    "LCK": ["finds caps in every couch cushion", "survived three firefights by tripping at the right moment",
            "always gets the Quantum from the vending machine"],
}
LOW_LINES = {
    "STR": ["but needs both hands to lift a laser pistol", "but gets winded opening a can of Pork n' Beans"],
    "PER": ["yet has walked into the same lamppost twice", "yet couldn't spot a super mutant in a phone booth"],
    "END": ["though a single radroach bite means a week in bed", "though they catch a cold just thinking about rain"],
    "CHA": ["but their small talk peaks at grunting", "but merchants mysteriously raise prices when they walk in"],
    "INT": ["but firmly believes Nuka-Cola is a food group", "but still can't find the Pip-Boy's flashlight"],
    "AGI": ["but trips over their own shadow", "but sneaks like a brahmin in a tin shop"],
    "LCK": ["but if there's one landmine in the wasteland, they'll find it", "but every vending machine eats their caps"],
}
PERK_LINES = {
    "Iron Fist": "Punches first, asks questions never.",
    "Piercing Strike": "Collects knife-sharpening stones like trophies.",
    "Paralyzing Palm": "Learned a 'secret technique' from a pre-war holotape.",
    "Slayer": "Fights end fast and messy when they're around.",
    "Adrenaline Rush": "Gets scarier the more they bleed.",
    "Big Leagues": "Still practicing for a baseball season that ended in 2077.",
    "Basher": "Thinks the stock of a rifle is the business end.",
    "Pain Train": "Announces every charge with a train whistle. Choo choo.",
    "Adamantium Skeleton": "Has walked off falls that should've been fatal.",
    "Quick Draw": "Hands are a blur whenever someone says 'draw'.",
    "Center Mass": "Aims for the chest because 'it's the big bit'.",
    "Quick Hands": "Fans the hammer like a pre-war movie cowboy.",
    "Steady Aim": "Breathes out slowly before every single shot.",
    "Gun Fu": "Fires at two targets at once and calls it style.",
    "Moving Target": "Never stands still in a fight. Or in a conversation.",
    "Sniper": "Can name the exact rib they plan to hit.",
    "Awareness": "Studies people the way others study maps.",
    "Concentrated Fire": "Keeps firing at the same spot until something gives.",
    "Night Person": "Sleeps all day, prowls all night.",
    "Smooth Talker": "Has an answer for everything, usually a good one.",
    "Scoundrel": "Lies so smoothly they sometimes believe it themselves.",
    "Cap Collector": "Haggles over every single cap, on principle.",
    "Black Widow": "Leaves a trail of broken hearts across the wastes.",
    "Lady Killer": "Leaves a trail of broken hearts across the wastes.",
    "Inspirational": "Gives rousing speeches at the worst possible moments.",
    "Junktown Jerky Vendor": "Could sell sand to a Mojave raider.",
    "Dogmeat": "Never goes anywhere without a very good dog.",
    "Animal Friend": "Wild animals tend to just... like them.",
    "Armorer": "Bolts scrap metal onto everyone's coats, asked or not.",
    "Hacker": "Can't walk past a terminal without 'having a look'.",
    "Jury Rigging": "Holds the world together with duct tape and hope.",
    "Comprehension": "Reads every magazine twice and quotes it constantly.",
    "Nuclear Physicist": "Hums happily whenever the Geiger counter clicks.",
    "Chemist": "Brews mystery chems in an old cooking pot.",
    "Medic": "Patches people up whether they want it or not.",
    "Healer": "Always has a bandage and a lecture ready.",
    "Faster Healing": "Wounds close up suspiciously fast.",
    "Fast Metabolism": "Is always hungry, and always healing.",
    "Ninja": "You won't hear them coming. Nobody ever does.",
    "Infiltrator": "Treats every locked door as a personal insult.",
    "Mister Sandman": "Hums a lullaby before every silent takedown.",
    "Light Step": "Moves like a cat around pressure plates.",
    "Ghost": "Disappears into shadows mid-sentence.",
    "Master Thief": "Your caps are already in their pocket.",
    "Pickpocket": "Shakes hands and walks off with your watch.",
    "Hunter": "Wears trophies from every mutant beast they've bagged.",
    "Pathfinder": "Knows a shortcut everywhere. Some of them even work.",
    "Lead Belly": "Drinks straight from irradiated puddles.",
    "Aquaboy": "Happier underwater than on land.",
    "Aquagirl": "Happier underwater than on land.",
    "Snakeater": "Has been bitten by everything and shrugged it off.",
    "Rad Resistance": "Glows a little, but in a healthy way.",
    "Entomologist": "Names every bloatfly before killing it.",
    "Solar Powered": "Sunbathes at noon to 'recharge'.",
    "Demolition Expert": "Signs their work with a scorch mark.",
    "Heave Ho!": "Throws grenades like a pre-war quarterback.",
    "Bloody Mess": "Things tend to explode messily around them.",
    "Daring Nature": "Takes every bet, especially the stupid ones.",
    "Cautious Nature": "Checks every corner twice. Then once more.",
    "Mysterious Stranger": "A man in a trench coat seems to follow them around.",
    "Better Criticals": "Somehow always hits right where it hurts.",
    "Can Do!": "Finds canned food in places no one else looks.",
    "Scrounger": "Pockets jingle with spare ammo at all times.",
    "Grim Reaper's Sprint": "Gets a burst of energy after every kill.",
    "Pharma Farma": "Medicine cabinets just seem to open up for them.",
    "Toughness": "Skin like old saddle leather.",
    "Size Matters": "Believes every problem can be solved with a bigger gun.",
    "Strong Back": "Carries everyone's loot. Charges for it.",
    "Chem Resistant": "Has tried every chem in the wasteland and kicked them all.",
    "Refractor": "Laser beams seem to bend away from them.",
    "Meltdown": "Leaves glowing piles where enemies used to be.",
    "Action Boy": "Always has energy for one more move.",
    "Action Girl": "Always has energy for one more move.",
    "Blitz": "Closes distance before you can blink.",
    "Finesse": "Makes every hit count, with flair.",
    "Party Boy": "Brings the party, and the bottles.",
    "Party Girl": "Brings the party, and the bottles.",
    "Shotgun Surgeon": "Calls a shotgun blast 'outpatient surgery'.",
}
ORIGIN_LINES = {
    "Brotherhood Initiate": ["Salutes holotapes of Elder Maxson before bed.",
                             "Keeps a list of 'technology to reclaim' that includes your toaster."],
    "Ghoul": ["Still quotes pre-war prices and complains loudly.",
              "Remembers the bombs and won't stop talking about them."],
    "Super Mutant": ["Insists on being called 'small' as a joke.",
                     "Is surprisingly gentle with kittens and brahmin calves."],
    "Mister Handy": ["Polishes everyone's boots, asked or not.",
                     "Still keeps a daily cleaning schedule for a house that's long gone."],
    "Survivor": ["Trusts nobody until they've shared a meal.",
                 "Carves a notch on their gear after every close call."],
    "Vault Dweller": ["Still shocked by the sky every morning.",
                      "Quotes Vault-Tec safety posters word for word."],
}
